const JSON_SCHEMA_KEYWORDS = [
  '$id',
  '$schema',
  '$comment',
  'type',
  'properties',
  'items',
  'required',
  'enum',
  'const',
  'additionalProperties',
  'patternProperties',
  'description',
  'title',
  'default',
  'errorMessage',
  'validators',
  'collection',
  'format',
  'minimum',
  'maximum',
  'minLength',
  'maxLength',
  'minItems',
  'maxItems',
  'uniqueItems',
  'input',
  'label',
  'options',
  'placeholder',
  'disabled',
  'mimeTypes',
  'pattern',
  'min',
  'max'
] as const

export default JSON_SCHEMA_KEYWORDS
