import { useEffect, useRef, useDeferredValue } from 'react'
import type { AggregationFunction, AggregationParams, ClientAggregationFunction } from '@teamplay/utils/aggregation'
import sub, { getSubResultSignal, unsub } from '../orm/sub.ts'
import { useScheduleUpdate, useCache, useDefer } from './helpers.ts'
import { useSuspenseGroupScheduleUpdate } from './wrapIntoSuspense.js'
import executionContextTracker from './executionContextTracker.ts'
import * as promiseBatcher from './promiseBatcher.ts'
import { getPrivateData } from '../orm/privateData.js'
import { isDocReady } from '../orm/queryReadiness.js'
import { getRoot, ROOT_ID } from '../orm/Root.ts'
import {
  COLLECTION_NAME,
  HASH,
  IS_QUERY,
  PARAMS,
  QUERIES,
  querySubscriptions,
  materializeQueryDataDocsToCollection
} from '../orm/Query.js'
import { AGGREGATIONS, IS_AGGREGATION, aggregationSubscriptions } from '../orm/Aggregation.js'
import { SEGMENTS } from '../orm/signalSymbols.ts'
import { getSubscriptionGcDelay } from '../orm/subscriptionGcDelay.ts'
import {
  isPublicDocumentSignal,
  type CollectionSignal,
  type ComputedQueryParamsInput,
  type DocumentSignal,
  type QueryParams,
  type RegisteredAggregationInput,
  type SignalBaseInstance,
  type SignalModelConstructor,
  type SubResult,
  type TypedAggregationInput,
  type TypedAggregationSignal,
  type WildcardSignalPath
} from '../orm/Signal.ts'

type RuntimeSub = (signal: unknown, params?: unknown) => unknown
const runtimeSub = sub as RuntimeSub

export interface UseSubOptions {
  /** Return `undefined` while loading instead of throwing a Suspense promise. */
  async?: boolean
  /** Defer re-subscriptions. Pass a number to use a custom delay. */
  defer?: boolean | number
  /** Batch Suspense promises across multiple subscriptions in one render attempt. */
  batch?: boolean
}

const USE_SUB_OPTION_KEYS = new Set<string>(['async', 'defer', 'batch'] satisfies Array<keyof UseSubOptions>)
const MAX_UNCOMMITTED_LEASE_GRACE_MS = 50

let TEST_THROTTLING: false | number = false

// experimental feature to leverage useDeferredValue() to handle re-subscriptions.
// Currently it does lead to issues with extra rerenders and requires further investigation
let USE_DEFERRED_VALUE: boolean = true
// by default we want to defer stuff if possible instead of throwing promises
let DEFAULT_DEFER: boolean = true

/**
 * Subscribe to a document signal in React async mode.
 * @param signal Document signal to subscribe to.
 * @param params Must be omitted for document subscriptions.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<TSignal extends DocumentSignal<any, any, any>> (
  signal: TSignal,
  options?: UseSubOptions
): SubResult<TSignal>

/**
 * Subscribe to a document signal in React async mode.
 * @param signal Document signal to subscribe to.
 * @param params Must be omitted for document subscriptions.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<TSignal extends DocumentSignal<any, any, any>> (
  signal: TSignal,
  params?: undefined,
  options?: UseSubOptions
): SubResult<TSignal>

/**
 * Subscribe to a collection query in React async mode.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params, including filters and `$sort`.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: QueryParams<TDocument>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, QueryParams<TDocument>>

/**
 * Subscribe to a collection query with computed string keys in React async mode.
 * This fallback preserves Mongo-style computed paths such as `{ [`likes.${id}`]: true }`.
 * Literal query objects should use the stricter overload above.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params with a widened computed key.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath,
  TParams extends object
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: TParams & ComputedQueryParamsInput<TParams>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, TParams>

/**
 * Subscribe to a registered collection aggregation in React async mode.
 * @param signal Aggregation header generated by StartupJS model loading.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<TCollection extends string, TOutput = unknown> (
  signal: RegisteredAggregationInput<TCollection, TOutput>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<RegisteredAggregationInput<TCollection, TOutput>>

/**
 * Subscribe to a client aggregation in React async mode.
 * @param signal Aggregation function created with `aggregation(collection, fn)`.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<TOutput, TCollection extends string> (
  signal: ClientAggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<ClientAggregationFunction<TOutput, TCollection>>

/**
 * Subscribe to an aggregation with explicit output typing in React async mode.
 * @param signal Typed aggregation input.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<
  TDocument,
  TDocumentModel extends SignalModelConstructor<TDocument>
> (
  signal: TypedAggregationInput<TDocument, TDocumentModel>,
  params?: AggregationParams,
  options?: UseSubOptions
): TypedAggregationSignal<TDocument, TDocumentModel>

/**
 * Subscribe to an unregistered aggregation in React async mode.
 * @param signal Aggregation function.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<TOutput = unknown, TCollection extends string = string> (
  signal: AggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<AggregationFunction<TOutput, TCollection>, AggregationParams | undefined>

export function useAsyncSub (signal: unknown, params?: unknown, options?: UseSubOptions): unknown {
  const normalized = normalizeUseSubArgs(signal, params, options)
  return useNormalizedSub(normalized.signal, normalized.params, { ...normalized.options, async: true })
}

/**
 * Close a batch subscription barrier opened by previous `useBatchSub()` calls in this render.
 */
export function useBatchSub (): void

/**
 * Subscribe to a document signal in React batch mode.
 * @param signal Document signal to subscribe to.
 * @param params Must be omitted for document subscriptions.
 * @param options Subscription behavior options.
 */
export function useBatchSub<TSignal extends DocumentSignal<any, any, any>> (
  signal: TSignal,
  options?: UseSubOptions
): SubResult<TSignal>

/**
 * Subscribe to a document signal in React batch mode.
 * @param signal Document signal to subscribe to.
 * @param params Must be omitted for document subscriptions.
 * @param options Subscription behavior options.
 */
export function useBatchSub<TSignal extends DocumentSignal<any, any, any>> (
  signal: TSignal,
  params?: undefined,
  options?: UseSubOptions
): SubResult<TSignal>

/**
 * Subscribe to a collection query in React batch mode.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params, including filters and `$sort`.
 * @param options Subscription behavior options.
 */
export function useBatchSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: QueryParams<TDocument>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, QueryParams<TDocument>>

/**
 * Subscribe to a collection query with computed string keys in React batch mode.
 * This fallback preserves Mongo-style computed paths such as `{ [`likes.${id}`]: true }`.
 * Literal query objects should use the stricter overload above.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params with a widened computed key.
 * @param options Subscription behavior options.
 */
export function useBatchSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath,
  TParams extends object
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: TParams & ComputedQueryParamsInput<TParams>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, TParams>

/**
 * Subscribe to a registered collection aggregation in React batch mode.
 * @param signal Aggregation header generated by StartupJS model loading.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useBatchSub<TCollection extends string, TOutput = unknown> (
  signal: RegisteredAggregationInput<TCollection, TOutput>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<RegisteredAggregationInput<TCollection, TOutput>>

/**
 * Subscribe to a client aggregation in React batch mode.
 * @param signal Aggregation function created with `aggregation(collection, fn)`.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useBatchSub<TOutput, TCollection extends string> (
  signal: ClientAggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<ClientAggregationFunction<TOutput, TCollection>>

/**
 * Subscribe to an aggregation with explicit output typing in React batch mode.
 * @param signal Typed aggregation input.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useBatchSub<
  TDocument,
  TDocumentModel extends SignalModelConstructor<TDocument>
> (
  signal: TypedAggregationInput<TDocument, TDocumentModel>,
  params?: AggregationParams,
  options?: UseSubOptions
): TypedAggregationSignal<TDocument, TDocumentModel>

/**
 * Subscribe to an unregistered aggregation in React batch mode.
 * @param signal Aggregation function.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useBatchSub<TOutput = unknown, TCollection extends string = string> (
  signal: AggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<AggregationFunction<TOutput, TCollection>, AggregationParams | undefined>

export function useBatchSub (signal?: unknown, params?: unknown, options?: UseSubOptions): unknown {
  const callUseSub = useSub as (signal: unknown, params?: unknown, options?: UseSubOptions) => unknown
  if (arguments.length === 0) {
    return callUseSub(undefined, undefined, { batch: true })
  }
  const normalized = normalizeUseSubArgs(signal, params, options)
  return callUseSub(normalized.signal, normalized.params, { ...normalized.options, async: false, batch: true })
}

/**
 * Close a batch subscription barrier opened by previous `useSub(..., { batch: true })`
 * calls in this render.
 */
export default function useSub (
  signal: undefined,
  params: undefined,
  options: UseSubOptions & { batch: true }
): void

/**
 * Subscribe to a document signal in React.
 * @param signal Document signal to subscribe to.
 * @param params Must be omitted for document subscriptions.
 * @param options Subscription behavior options.
 */
export default function useSub<TSignal extends DocumentSignal<any, any, any>> (
  signal: TSignal,
  options?: UseSubOptions
): SubResult<TSignal>

/**
 * Subscribe to a document signal in React.
 * @param signal Document signal to subscribe to.
 * @param params Must be omitted for document subscriptions.
 * @param options Subscription behavior options.
 */
export default function useSub<TSignal extends DocumentSignal<any, any, any>> (
  signal: TSignal,
  params?: undefined,
  options?: UseSubOptions
): SubResult<TSignal>

/**
 * Subscribe to a collection query in React.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params, including filters and `$sort`.
 * @param options Subscription behavior options.
 */
export default function useSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: QueryParams<TDocument>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, QueryParams<TDocument>>

/**
 * Subscribe to a collection query with computed string keys in React.
 * This fallback preserves Mongo-style computed paths such as `{ [`likes.${id}`]: true }`.
 * Literal query objects should use the stricter overload above.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params with a widened computed key.
 * @param options Subscription behavior options.
 */
export default function useSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath,
  TParams extends object
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: TParams & ComputedQueryParamsInput<TParams>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, TParams>

/**
 * Subscribe to a registered collection aggregation in React.
 * @param signal Aggregation header generated by StartupJS model loading.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export default function useSub<TCollection extends string, TOutput = unknown> (
  signal: RegisteredAggregationInput<TCollection, TOutput>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<RegisteredAggregationInput<TCollection, TOutput>>

/**
 * Subscribe to a client aggregation in React.
 * @param signal Aggregation function created with `aggregation(collection, fn)`.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export default function useSub<TOutput, TCollection extends string> (
  signal: ClientAggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<ClientAggregationFunction<TOutput, TCollection>>

/**
 * Subscribe to an aggregation with explicit output typing in React.
 * @param signal Typed aggregation input.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export default function useSub<
  TDocument,
  TDocumentModel extends SignalModelConstructor<TDocument>
> (
  signal: TypedAggregationInput<TDocument, TDocumentModel>,
  params?: AggregationParams,
  options?: UseSubOptions
): TypedAggregationSignal<TDocument, TDocumentModel>

/**
 * Subscribe to an unregistered aggregation in React.
 * @param signal Aggregation function.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export default function useSub<TOutput = unknown, TCollection extends string = string> (
  signal: AggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<AggregationFunction<TOutput, TCollection>, AggregationParams | undefined>

export default function useSub (signal: unknown, params?: unknown, options?: UseSubOptions): unknown {
  const normalized = normalizeUseSubArgs(signal, params, options)
  return useNormalizedSub(normalized.signal, normalized.params, normalized.options)
}

function normalizeUseSubArgs (
  signal: unknown,
  params?: unknown,
  options?: UseSubOptions
): { signal: unknown, params?: unknown, options?: UseSubOptions } {
  if (options === undefined && params !== undefined && isPublicDocumentSignal(signal) && isUseSubOptions(params)) {
    return {
      signal,
      params: undefined,
      options: params
    }
  }
  return { signal, params, options }
}

function isUseSubOptions (value: unknown): value is UseSubOptions {
  if (value == null || typeof value !== 'object' || Array.isArray(value)) return false
  return Object.keys(value).every(key => USE_SUB_OPTION_KEYS.has(key))
}

function useNormalizedSub (signal: unknown, params?: unknown, options?: UseSubOptions): unknown {
  const scheduleGroupUpdate = useSuspenseGroupScheduleUpdate()
  if (isBatchBarrierCall(signal, params, options)) return closeBatchBarrier(scheduleGroupUpdate)
  if (USE_DEFERRED_VALUE) {
    return useSubDeferred(signal, params, options) // eslint-disable-line react-hooks/rules-of-hooks
  } else {
    return useSubClassic(signal, params, options) // eslint-disable-line react-hooks/rules-of-hooks
  }
}

function isBatchBarrierCall (signal: unknown, params: unknown, options?: UseSubOptions): boolean {
  return signal === undefined && params === undefined && !!options?.batch
}

function closeBatchBarrier (
  scheduleGroupUpdate: ((promise: PromiseLike<unknown>) => void) | undefined
): void {
  const promise = promiseBatcher.getPromiseAll()
  if (promise) {
    scheduleGroupUpdate?.(promise)
    throw promise
  }
}

// version of sub() which works as a react hook and throws promise for Suspense
export function useSubDeferred (
  signal: unknown,
  params?: unknown,
  { async = false, defer, batch = false }: UseSubOptions = {}
): unknown {
  const $signalRef = useRef<unknown>()
  const scheduleUpdate = useScheduleUpdate()
  const scheduleGroupUpdate = useSuspenseGroupScheduleUpdate()
  const observerDefer = useDefer()
  if (batch) promiseBatcher.activate()
  defer ??= observerDefer ?? DEFAULT_DEFER
  if (defer) {
    signal = useDeferredValue(signal) // eslint-disable-line react-hooks/rules-of-hooks
    const serializedParams = useDeferredValue(params ? JSON.stringify(params) : undefined) // eslint-disable-line react-hooks/rules-of-hooks
    params = serializedParams != null ? JSON.parse(serializedParams) : undefined
  }
  const subscriptionLease = useSubscriptionLease(signal, params)
  const promiseOrSignal = subscriptionLease.value
  // 1. if it's a promise, throw it so that Suspense can catch it and wait for subscription to finish
  if (isThenable(promiseOrSignal)) {
    const promise = maybeThrottle(promiseOrSignal)
    const readyPromise = getSubscriptionReadyPromise(promise, subscriptionLease)
    scheduleRenderAttemptLeaseCleanup(subscriptionLease, readyPromise, batch)
    const hasPreviousSignal = !!$signalRef.current
    if (batch) {
      // Batch suspense must block only on initial load.
      // On resubscribe we keep rendering previous signal and refresh in background.
      if (!hasPreviousSignal) {
        promiseBatcher.add(promise)
        addBatchReadinessCheck(promise, subscriptionLease)
      } else {
        scheduleUpdate(readyPromise)
      }
      if (async) scheduleUpdate(readyPromise)
      return $signalRef.current
    }
    if (async) {
      scheduleUpdate(readyPromise)
      return
    }
    // Keep previous snapshot during update re-subscribe and refresh in background.
    if (hasPreviousSignal) {
      scheduleUpdate(readyPromise)
      return $signalRef.current
    }
    scheduleGroupUpdate?.(readyPromise)
    throw readyPromise
  // 2. if it's a signal, we save it into ref to make sure it's not garbage collected while component exists
  } else {
    const $signal = promiseOrSignal
    if (batch && !$signalRef.current) addBatchReadinessCheckForSignal($signal, subscriptionLease)
    if ($signalRef.current !== $signal) $signalRef.current = $signal
    return $signal
  }
}

// classic version which initially throws promise for Suspense
// but if we get a promise second time, we return the last signal and wait for promise to resolve
export function useSubClassic (
  signal: unknown,
  params?: unknown,
  { async = false, batch = false }: UseSubOptions = {}
): unknown {
  const id = executionContextTracker.newHookId()
  const cache = useCache(undefined)
  const scheduleUpdate = useScheduleUpdate()
  const scheduleGroupUpdate = useSuspenseGroupScheduleUpdate()
  if (batch) promiseBatcher.activate()
  const subscriptionLease = useSubscriptionLease(signal, params)
  const promiseOrSignal = subscriptionLease.value
  // 1. if it's a promise, throw it so that Suspense can catch it and wait for subscription to finish
  if (isThenable(promiseOrSignal)) {
    const promise = maybeThrottle(promiseOrSignal)
    const readyPromise = getSubscriptionReadyPromise(promise, subscriptionLease)
    scheduleRenderAttemptLeaseCleanup(subscriptionLease, readyPromise, batch)
    if (batch) {
      const hasPreviousSignal = cache.has(id)
      // Batch suspense must block only on initial load.
      // On resubscribe we keep rendering previous signal and refresh in background.
      if (!hasPreviousSignal) {
        promiseBatcher.add(promise)
        addBatchReadinessCheck(promise, subscriptionLease)
      } else {
        scheduleUpdate(readyPromise)
      }
      if (async) scheduleUpdate(readyPromise)
      if (hasPreviousSignal) return cache.get(id)
      return
    }
    // first time we just throw the promise to be caught by Suspense
    if (!cache.has(id)) {
      // if we are in async mode, we just return nothing and let the user
      // handle appearance of signal on their own.
      // We manually schedule an update when promise resolves since we can't
      // rely on Suspense in this case to automatically trigger component's re-render
      if (async) {
        scheduleUpdate(readyPromise)
        return
      }
      // in regular mode we throw the promise to be caught by Suspense
      // this way we guarantee that the signal with all the data
      // will always be there when component is rendered
      scheduleGroupUpdate?.(readyPromise)
      throw readyPromise
    }
    // if we already have a previous signal, we return it and wait for new promise to resolve
    scheduleUpdate(readyPromise)
    return cache.get(id)
  // 2. if it's a signal, we save it into ref to make sure it's not garbage collected while component exists
  } else {
    const $signal = promiseOrSignal
    if (batch && !cache.has(id)) addBatchReadinessCheckForSignal($signal, subscriptionLease)
    if (cache.get(id) !== $signal) {
      cache.set(id, $signal)
    }
    return $signal
  }
}

export function setTestThrottling (ms: number): void {
  if (typeof ms !== 'number') throw Error('setTestThrottling() accepts only a number in ms')
  if (ms === 0) throw Error('setTestThrottling(0) is not allowed, use resetTestThrottling() instead')
  if (ms < 0) throw Error('setTestThrottling() accepts only a positive number in ms')
  TEST_THROTTLING = ms
}
export function resetTestThrottling (): void {
  TEST_THROTTLING = false
}
export function setUseDeferredValue (value: boolean): void {
  USE_DEFERRED_VALUE = value
}
export function setDefaultDefer (value: boolean): void {
  DEFAULT_DEFER = value
}

interface SubscriptionLease {
  value: unknown
  signal?: unknown
  signalDisposed: boolean
  inputSignal?: unknown
  serializedParams?: string
  previousLease?: SubscriptionLease
  committed: boolean
  released: boolean
  cleanupTimer?: ReturnType<typeof setTimeout>
  releaseTimer?: ReturnType<typeof setTimeout>
  unregisterCacheDestroy?: () => void
}

function useSubscriptionLease (signal: unknown, params?: unknown): SubscriptionLease {
  const cache = useCache(undefined)
  const hookId = executionContextTracker.newHookId()
  const cacheKey = `subscriptionLease:${hookId}`
  const serializedParams = params != null ? JSON.stringify(params) : undefined
  let lease = cache.get(cacheKey) as SubscriptionLease | undefined
  if (
    !lease ||
    lease.released ||
    lease.inputSignal !== signal ||
    lease.serializedParams !== serializedParams
  ) {
    const nextLease = createSubscriptionLease(signal, params, serializedParams, lease)
    nextLease.unregisterCacheDestroy = cache.onDestroy(() => releaseSubscriptionLease(nextLease))
    lease = nextLease
    cache.set(cacheKey, nextLease)
  } else {
    clearTimeout(lease.cleanupTimer)
    lease.cleanupTimer = undefined
  }

  useEffect(() => {
    lease.committed = true
    clearTimeout(lease.cleanupTimer)
    lease.cleanupTimer = undefined
    clearTimeout(lease.releaseTimer)
    lease.releaseTimer = undefined
    if (lease.previousLease) {
      clearTimeout(lease.previousLease.releaseTimer)
      lease.previousLease.releaseTimer = undefined
    }
    return () => scheduleSubscriptionLeaseRelease(lease)
  }, [lease])

  useEffect(() => {
    if (isThenable(lease.value)) return
    releasePreviousSubscriptionLease(lease)
  })

  return lease
}

function createSubscriptionLease (
  signal: unknown,
  params: unknown,
  serializedParams?: string,
  previousLease?: SubscriptionLease
): SubscriptionLease {
  const value = params != null ? runtimeSub(signal, params) : runtimeSub(signal)
  const lease: SubscriptionLease = {
    value,
    signal: getSubResultSignal(value),
    inputSignal: signal,
    serializedParams,
    previousLease: previousLease?.released ? undefined : previousLease,
    committed: false,
    released: false,
    signalDisposed: false
  }

  if (isThenable(value)) {
    Promise.resolve(value).then($signal => {
      lease.signal = $signal
      lease.value = $signal
      if (lease.released) {
        disposeSubscriptionLeaseSignal(lease)
      }
    }, ignoreSubscriptionCleanupError)
  }

  return lease
}

function scheduleUncommittedLeaseCleanupAfter (
  lease: SubscriptionLease,
  promise: PromiseLike<unknown>
): void {
  Promise.resolve(promise).then(
    () => scheduleUncommittedLeaseCleanup(lease),
    () => scheduleUncommittedLeaseCleanup(lease)
  )
}

function scheduleRenderAttemptLeaseCleanup (
  lease: SubscriptionLease,
  readyPromise: PromiseLike<unknown>,
  batch: boolean
): void {
  if (!batch) {
    scheduleUncommittedLeaseCleanupAfter(lease, readyPromise)
    return
  }
  promiseBatcher.addRenderAttemptCleanup(barrier => {
    scheduleUncommittedLeaseCleanupAfter(lease, barrier ?? readyPromise)
  })
}

function scheduleUncommittedLeaseCleanup (lease: SubscriptionLease): void {
  if (lease.committed || lease.released || lease.cleanupTimer) return
  lease.cleanupTimer = setTimeout(() => {
    lease.cleanupTimer = undefined
    if (!lease.committed) releaseSubscriptionLease(lease)
  }, Math.min(getSubscriptionGcDelay(), MAX_UNCOMMITTED_LEASE_GRACE_MS))
}

function releaseSubscriptionLease (lease: SubscriptionLease): void {
  if (lease.released) return
  const previousLease = lease.previousLease
  lease.previousLease = undefined
  lease.released = true
  lease.unregisterCacheDestroy?.()
  lease.unregisterCacheDestroy = undefined
  clearTimeout(lease.cleanupTimer)
  lease.cleanupTimer = undefined
  clearTimeout(lease.releaseTimer)
  lease.releaseTimer = undefined
  disposeSubscriptionLeaseSignal(lease)
  if (lease.committed && previousLease) releaseSubscriptionLease(previousLease)
}

function releasePreviousSubscriptionLease (lease: SubscriptionLease): void {
  const previousLease = lease.previousLease
  if (!previousLease) return
  lease.previousLease = undefined
  releaseSubscriptionLease(previousLease)
}

function scheduleSubscriptionLeaseRelease (lease: SubscriptionLease): void {
  if (lease.released || lease.releaseTimer) return
  lease.releaseTimer = setTimeout(() => {
    lease.releaseTimer = undefined
    releaseSubscriptionLease(lease)
  })
}

function disposeSubscriptionLeaseSignal (lease: SubscriptionLease): void {
  const signal = lease.signal
  lease.signal = undefined
  lease.inputSignal = undefined
  lease.serializedParams = undefined
  lease.value = undefined
  // A pending sub result exposes its signal before its promise settles. If this
  // lease was released while pending, the resolution callback sees the same
  // acquisition again and must not unsubscribe another owner's matching record.
  if (!signal || lease.signalDisposed) return
  lease.signalDisposed = true
  Promise.resolve(unsub(signal)).catch(ignoreSubscriptionCleanupError)
}

function ignoreSubscriptionCleanupError (): void {}

// throttle to simulate slow network
function maybeThrottle<TValue> (promise: Promise<TValue>): Promise<TValue> {
  const delay = TEST_THROTTLING
  if (delay === false) return promise
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      promise.then(resolve, reject)
    }, delay)
  })
}

function addBatchReadinessCheck (
  promise: PromiseLike<unknown>,
  lease?: SubscriptionLease
): void {
  let resolvedSignal: unknown
  let resolved = false
  promise.then(signal => {
    resolvedSignal = signal
    resolved = true
  }, () => {
    resolved = true
  })
  promiseBatcher.addCheck({
    key: promise,
    type: 'subscription',
    isReady: () => !!lease?.released || (resolved && isSubscriptionSignalReady(resolvedSignal)),
    getState: () => getBatchSignalState(resolvedSignal)
  })
}

function getSubscriptionReadyPromise (
  promise: PromiseLike<unknown>,
  lease?: SubscriptionLease
): Promise<unknown> {
  return Promise.resolve(promise).then(async signal => {
    await waitForSubscriptionSignalReady(signal, lease)
    return signal
  })
}

async function waitForSubscriptionSignalReady (
  signal: unknown,
  lease?: SubscriptionLease
): Promise<void> {
  while (!lease?.released && !isSubscriptionSignalReady(signal)) {
    await new Promise(resolve => setTimeout(resolve, 16))
  }
}

function addBatchReadinessCheckForSignal (
  signal: unknown,
  lease?: SubscriptionLease
): void {
  if (isSubscriptionSignalReady(signal)) return
  const promise = Promise.resolve(signal)
  promiseBatcher.add(promise)
  addBatchReadinessCheck(promise, lease)
}

function isSubscriptionSignalReady (signal: unknown): boolean {
  if (isPublicDocumentSignal(signal)) {
    const $doc = signal as SignalBaseInstance
    return isDocReady($doc[SEGMENTS])
  }
  if (isQuerySignal(signal)) return isSubscriptionQueryReady(signal)
  return true
}

function isSubscriptionQueryReady (signal: BatchQuerySignal): boolean {
  const collection = signal[COLLECTION_NAME]
  const params = signal[PARAMS]
  if (!isBatchQueryTransportStable(signal)) return false
  const hasExtraResult = isExtraQuery(params)
  if (hasExtraResult) return readQueryExtra(signal) !== undefined

  const isAggregate = !!signal[IS_AGGREGATION] || isAggregationQuery(params)
  const docs = signal.get()
  if (isAggregate) {
    if (Array.isArray(docs)) return true
    return readQueryExtra(signal) !== undefined
  }

  if (!Array.isArray(docs)) return false
  materializeQueryDataDocsToCollection(collection, docs)
  const ids = signal.getIds()
  for (const id of ids) {
    if (id == null) continue
    if (!isDocReady([collection, id])) return false
  }
  return true
}

function isBatchQueryTransportStable (signal: BatchQuerySignal): boolean {
  const subscriptions = signal[IS_AGGREGATION] ? aggregationSubscriptions : querySubscriptions
  const entry = subscriptions.entries.get(signal[HASH])
  if (!entry) return false
  return entry.phase === 'stable' && entry.mode === entry.targetMode
}

function getBatchSignalState (signal: unknown): unknown {
  if (isPublicDocumentSignal(signal)) {
    const $doc = signal as SignalBaseInstance
    return {
      kind: 'doc',
      path: $doc[SEGMENTS],
      ready: isDocReady($doc[SEGMENTS])
    }
  }
  if (!isQuerySignal(signal)) return { kind: 'unknown', resolved: !!signal }

  const rootId = getRoot(signal as SignalBaseInstance)?.[ROOT_ID]
  const hash = signal[HASH]
  const collection = signal[COLLECTION_NAME]
  return {
    kind: signal[IS_AGGREGATION] ? 'aggregation' : 'query',
    collection,
    hash,
    ids: getPrivateData(rootId, [QUERIES, hash, 'ids'], true),
    hasDocs: Array.isArray(getPrivateData(rootId, [QUERIES, hash, 'docs'], true)),
    hasExtra: getPrivateData(rootId, [QUERIES, hash, 'extra'], true) !== undefined,
    hasAggregation: getPrivateData(rootId, [AGGREGATIONS, hash], true) !== undefined
  }
}

function readQueryExtra (signal: BatchQuerySignal): unknown {
  try {
    return signal.extra.get()
  } catch (err) {
    if (isThenable(err)) return undefined
    throw err
  }
}

interface BatchQuerySignal extends SignalBaseInstance {
  readonly [COLLECTION_NAME]: string
  readonly [HASH]: string
  readonly [PARAMS]?: unknown
  readonly [IS_QUERY]?: unknown
  readonly [IS_AGGREGATION]?: unknown
  readonly extra: SignalBaseInstance
}

function isQuerySignal (signal: unknown): signal is BatchQuerySignal {
  return !!signal &&
    (typeof signal === 'object' || typeof signal === 'function') &&
    !!(signal as BatchQuerySignal)[IS_QUERY] &&
    typeof (signal as BatchQuerySignal)[COLLECTION_NAME] === 'string' &&
    typeof (signal as BatchQuerySignal)[HASH] === 'string'
}

function isExtraQuery (query: unknown): boolean {
  if (!query || typeof query !== 'object') return false
  return !!(
    (query as Record<string, unknown>).$count ||
    (query as Record<string, unknown>).$queryName ||
    (query as Record<string, unknown>).$aggregationName
  )
}

function isAggregationQuery (query: unknown): boolean {
  if (!query || typeof query !== 'object') return false
  return !!(
    (query as Record<string, unknown>).$aggregate ||
    (query as Record<string, unknown>).$aggregationName
  )
}

function isThenable<TValue = unknown> (value: unknown): value is Promise<TValue> {
  return !!value &&
    (typeof value === 'object' || typeof value === 'function') &&
    typeof (value as { then?: unknown }).then === 'function'
}
