import { useRef, useDeferredValue } from 'react'
import type { AggregationFunction, AggregationParams, ClientAggregationFunction } from '@teamplay/utils/aggregation'
import sub from '../orm/sub.ts'
import { useScheduleUpdate, useCache, useDefer, useId } from './helpers.ts'
import executionContextTracker from './executionContextTracker.ts'
import * as promiseBatcher from './promiseBatcher.ts'
import renderAttemptDestroyer from './renderAttemptDestroyer.ts'
import { markCompatComponent } from './compatComponentRegistry.ts'
import type {
  CollectionSignal,
  ComputedQueryParamsInput,
  DocumentSignal,
  QueryParams,
  RegisteredAggregationInput,
  SignalModelConstructor,
  SubResult,
  TypedAggregationInput,
  TypedAggregationSignal,
  WildcardSignalPath
} from '../orm/Signal.ts'

type RuntimeSub = (signal: unknown, params?: unknown) => unknown
const runtimeSub = sub as RuntimeSub

export interface UseSubOptions {
  /** Return `undefined` while loading instead of throwing a Suspense promise. */
  async?: boolean
  /** Defer re-subscriptions. Pass a number to use a custom delay. */
  defer?: boolean | number
  /** Batch Suspense promises across multiple subscriptions in one render attempt. */
  batch?: boolean
  /** Enable compatibility cleanup for legacy observer render attempts. */
  compatAttemptCleanup?: boolean
}

let TEST_THROTTLING: false | number = false

// experimental feature to leverage useDeferredValue() to handle re-subscriptions.
// Currently it does lead to issues with extra rerenders and requires further investigation
let USE_DEFERRED_VALUE: boolean = true
// by default we want to defer stuff if possible instead of throwing promises
let DEFAULT_DEFER: boolean = true

/**
 * Subscribe to a document signal in React async mode.
 * @param signal Document signal to subscribe to.
 * @param params Must be omitted for document subscriptions.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<TSignal extends DocumentSignal<any, any, any>> (
  signal: TSignal,
  params?: undefined,
  options?: UseSubOptions
): SubResult<TSignal>

/**
 * Subscribe to a collection query in React async mode.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params, including filters and `$sort`.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: QueryParams<TDocument>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, QueryParams<TDocument>>

/**
 * Subscribe to a collection query with computed string keys in React async mode.
 * This fallback preserves Mongo-style computed paths such as `{ [`likes.${id}`]: true }`.
 * Literal query objects should use the stricter overload above.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params with a widened computed key.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath,
  TParams extends object
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: TParams & ComputedQueryParamsInput<TParams>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, TParams>

/**
 * Subscribe to a registered collection aggregation in React async mode.
 * @param signal Aggregation header generated by StartupJS model loading.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<TCollection extends string, TOutput = unknown> (
  signal: RegisteredAggregationInput<TCollection, TOutput>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<RegisteredAggregationInput<TCollection, TOutput>>

/**
 * Subscribe to a client aggregation in React async mode.
 * @param signal Aggregation function created with `aggregation(collection, fn)`.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<TOutput, TCollection extends string> (
  signal: ClientAggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<ClientAggregationFunction<TOutput, TCollection>>

/**
 * Subscribe to an aggregation with explicit output typing in React async mode.
 * @param signal Typed aggregation input.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<
  TDocument,
  TDocumentModel extends SignalModelConstructor<TDocument>
> (
  signal: TypedAggregationInput<TDocument, TDocumentModel>,
  params?: AggregationParams,
  options?: UseSubOptions
): TypedAggregationSignal<TDocument, TDocumentModel>

/**
 * Subscribe to an unregistered aggregation in React async mode.
 * @param signal Aggregation function.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export function useAsyncSub<TOutput = unknown, TCollection extends string = string> (
  signal: AggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<AggregationFunction<TOutput, TCollection>, AggregationParams | undefined>

export function useAsyncSub (signal: unknown, params?: unknown, options?: UseSubOptions): unknown {
  return runUseSub(signal, params, { ...options, async: true })
}

/**
 * Subscribe to a document signal in React.
 * @param signal Document signal to subscribe to.
 * @param params Must be omitted for document subscriptions.
 * @param options Subscription behavior options.
 */
export default function useSub<TSignal extends DocumentSignal<any, any, any>> (
  signal: TSignal,
  params?: undefined,
  options?: UseSubOptions
): SubResult<TSignal>

/**
 * Subscribe to a collection query in React.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params, including filters and `$sort`.
 * @param options Subscription behavior options.
 */
export default function useSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: QueryParams<TDocument>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, QueryParams<TDocument>>

/**
 * Subscribe to a collection query with computed string keys in React.
 * This fallback preserves Mongo-style computed paths such as `{ [`likes.${id}`]: true }`.
 * Literal query objects should use the stricter overload above.
 * @param signal Collection signal to query.
 * @param params Mongo-style query params with a widened computed key.
 * @param options Subscription behavior options.
 */
export default function useSub<
  TDocument,
  TCollectionModel extends SignalModelConstructor<TDocument[]>,
  TDocumentModel extends SignalModelConstructor<TDocument>,
  TCollectionPath extends WildcardSignalPath,
  TParams extends object
> (
  signal: CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>,
  params: TParams & ComputedQueryParamsInput<TParams>,
  options?: UseSubOptions
): SubResult<CollectionSignal<TDocument, TCollectionModel, TDocumentModel, TCollectionPath>, TParams>

/**
 * Subscribe to a registered collection aggregation in React.
 * @param signal Aggregation header generated by StartupJS model loading.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export default function useSub<TCollection extends string, TOutput = unknown> (
  signal: RegisteredAggregationInput<TCollection, TOutput>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<RegisteredAggregationInput<TCollection, TOutput>>

/**
 * Subscribe to a client aggregation in React.
 * @param signal Aggregation function created with `aggregation(collection, fn)`.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export default function useSub<TOutput, TCollection extends string> (
  signal: ClientAggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<ClientAggregationFunction<TOutput, TCollection>>

/**
 * Subscribe to an aggregation with explicit output typing in React.
 * @param signal Typed aggregation input.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export default function useSub<
  TDocument,
  TDocumentModel extends SignalModelConstructor<TDocument>
> (
  signal: TypedAggregationInput<TDocument, TDocumentModel>,
  params?: AggregationParams,
  options?: UseSubOptions
): TypedAggregationSignal<TDocument, TDocumentModel>

/**
 * Subscribe to an unregistered aggregation in React.
 * @param signal Aggregation function.
 * @param params Parameters passed to the aggregation.
 * @param options Subscription behavior options.
 */
export default function useSub<TOutput = unknown, TCollection extends string = string> (
  signal: AggregationFunction<TOutput, TCollection>,
  params?: AggregationParams,
  options?: UseSubOptions
): SubResult<AggregationFunction<TOutput, TCollection>, AggregationParams | undefined>

export default function useSub (signal: unknown, params?: unknown, options?: UseSubOptions): unknown {
  return runUseSub(signal, params, options)
}

function runUseSub (signal: unknown, params?: unknown, options?: UseSubOptions): unknown {
  if (USE_DEFERRED_VALUE) {
    return useSubDeferred(signal, params, options) // eslint-disable-line react-hooks/rules-of-hooks
  } else {
    return useSubClassic(signal, params, options) // eslint-disable-line react-hooks/rules-of-hooks
  }
}

// version of sub() which works as a react hook and throws promise for Suspense
export function useSubDeferred (
  signal: unknown,
  params?: unknown,
  { async = false, defer, batch = false, compatAttemptCleanup = false }: UseSubOptions = {}
): unknown {
  const $signalRef = useRef<unknown>()
  const componentId = useId()
  const scheduleUpdate = useScheduleUpdate()
  const observerDefer = useDefer()
  if (compatAttemptCleanup) markCompatComponent(componentId)
  if (batch) promiseBatcher.activate()
  defer ??= observerDefer ?? DEFAULT_DEFER
  if (defer) {
    signal = useDeferredValue(signal) // eslint-disable-line react-hooks/rules-of-hooks
    const serializedParams = useDeferredValue(params ? JSON.stringify(params) : undefined) // eslint-disable-line react-hooks/rules-of-hooks
    params = serializedParams != null ? JSON.parse(serializedParams) : undefined
  }
  const promiseOrSignal = params != null ? runtimeSub(signal, params) : runtimeSub(signal)
  // 1. if it's a promise, throw it so that Suspense can catch it and wait for subscription to finish
  if (isThenable(promiseOrSignal)) {
    const promise = maybeThrottle(promiseOrSignal)
    const hasPreviousSignal = !!$signalRef.current
    if (batch) {
      // Batch suspense must block only on initial load.
      // On resubscribe we keep rendering previous signal and refresh in background.
      if (!hasPreviousSignal) {
        promiseBatcher.add(promise)
        if (compatAttemptCleanup) registerCompatAttemptCleanup(signal, params)
      } else {
        scheduleUpdate(promise)
      }
      if (async) scheduleUpdate(promise)
      return $signalRef.current
    }
    if (async) {
      scheduleUpdate(promise)
      return
    }
    // Keep previous snapshot during update re-subscribe and refresh in background.
    if (hasPreviousSignal) {
      scheduleUpdate(promise)
      return $signalRef.current
    }
    if (compatAttemptCleanup) registerCompatAttemptCleanup(signal, params)
    throw promise
  // 2. if it's a signal, we save it into ref to make sure it's not garbage collected while component exists
  } else {
    const $signal = promiseOrSignal
    if ($signalRef.current !== $signal) $signalRef.current = $signal
    return $signal
  }
}

// classic version which initially throws promise for Suspense
// but if we get a promise second time, we return the last signal and wait for promise to resolve
export function useSubClassic (
  signal: unknown,
  params?: unknown,
  { async = false, batch = false, compatAttemptCleanup = false }: UseSubOptions = {}
): unknown {
  const id = executionContextTracker.newHookId()
  const componentId = useId()
  const cache = useCache(undefined)
  const scheduleUpdate = useScheduleUpdate()
  if (compatAttemptCleanup) markCompatComponent(componentId)
  if (batch) promiseBatcher.activate()
  const promiseOrSignal = params != null ? runtimeSub(signal, params) : runtimeSub(signal)
  // 1. if it's a promise, throw it so that Suspense can catch it and wait for subscription to finish
  if (isThenable(promiseOrSignal)) {
    const promise = maybeThrottle(promiseOrSignal)
    if (batch) {
      const hasPreviousSignal = cache.has(id)
      // Batch suspense must block only on initial load.
      // On resubscribe we keep rendering previous signal and refresh in background.
      if (!hasPreviousSignal) {
        promiseBatcher.add(promise)
        if (compatAttemptCleanup) registerCompatAttemptCleanup(signal, params)
      } else {
        scheduleUpdate(promise)
      }
      if (async) scheduleUpdate(promise)
      if (hasPreviousSignal) return cache.get(id)
      return
    }
    // first time we just throw the promise to be caught by Suspense
    if (!cache.has(id)) {
      // if we are in async mode, we just return nothing and let the user
      // handle appearance of signal on their own.
      // We manually schedule an update when promise resolves since we can't
      // rely on Suspense in this case to automatically trigger component's re-render
      if (async) {
        scheduleUpdate(promise)
        return
      }
      if (compatAttemptCleanup) registerCompatAttemptCleanup(signal, params)
      // in regular mode we throw the promise to be caught by Suspense
      // this way we guarantee that the signal with all the data
      // will always be there when component is rendered
      throw promise
    }
    // if we already have a previous signal, we return it and wait for new promise to resolve
    scheduleUpdate(promise)
    return cache.get(id)
  // 2. if it's a signal, we save it into ref to make sure it's not garbage collected while component exists
  } else {
    const $signal = promiseOrSignal
    if (cache.get(id) !== $signal) {
      cache.set(id, $signal)
    }
    return $signal
  }
}

export function setTestThrottling (ms: number): void {
  if (typeof ms !== 'number') throw Error('setTestThrottling() accepts only a number in ms')
  if (ms === 0) throw Error('setTestThrottling(0) is not allowed, use resetTestThrottling() instead')
  if (ms < 0) throw Error('setTestThrottling() accepts only a positive number in ms')
  TEST_THROTTLING = ms
}
export function resetTestThrottling (): void {
  TEST_THROTTLING = false
}
export function setUseDeferredValue (value: boolean): void {
  USE_DEFERRED_VALUE = value
}
export function setDefaultDefer (value: boolean): void {
  DEFAULT_DEFER = value
}

// throttle to simulate slow network
function maybeThrottle<TValue> (promise: Promise<TValue>): Promise<TValue> {
  const delay = TEST_THROTTLING
  if (delay === false) return promise
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      promise.then(resolve, reject)
    }, delay)
  })
}

function isThenable<TValue = unknown> (value: unknown): value is Promise<TValue> {
  return !!value &&
    (typeof value === 'object' || typeof value === 'function') &&
    typeof (value as { then?: unknown }).then === 'function'
}

function registerCompatAttemptCleanup (_signal: unknown, _params: unknown): void {
  // Compat hooks don't build per-hook init objects like Racer.
  // We still need a marker so trapRender can defer observer-shell cleanup
  // only when a real attempt cleanup exists.
  // This path must not arm suspense-gate keep-alive by itself.
  renderAttemptDestroyer.armCompatAttemptCleanup()
}
